from vgamepad import XUSB_BUTTON

BUTTON_INPUTS = {
    # Face Buttons
    60: XUSB_BUTTON.XUSB_GAMEPAD_A,
    64: XUSB_BUTTON.XUSB_GAMEPAD_B,
    67: XUSB_BUTTON.XUSB_GAMEPAD_X,
    72: XUSB_BUTTON.XUSB_GAMEPAD_Y,
    # Shoulder Buttons
    61: XUSB_BUTTON.XUSB_GAMEPAD_LEFT_SHOULDER,
    63: XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_SHOULDER,
    # Extra Buttons
    84: XUSB_BUTTON.XUSB_GAMEPAD_START,
    83: XUSB_BUTTON.XUSB_GAMEPAD_BACK,
    # D-PAD
    49: XUSB_BUTTON.XUSB_GAMEPAD_DPAD_LEFT,
    51: XUSB_BUTTON.XUSB_GAMEPAD_DPAD_DOWN,
    54: XUSB_BUTTON.XUSB_GAMEPAD_DPAD_UP,
    56: XUSB_BUTTON.XUSB_GAMEPAD_DPAD_RIGHT,
    # Thumb
    41: XUSB_BUTTON.XUSB_GAMEPAD_LEFT_THUMB,
    53: XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_THUMB,
}

STICK_MAPPING = {
    # Left JoyStick
    36: ("LX", -1),
    40: ("LX", +1),
    38: ("LY", -1),
    43: ("LY", +1),
    # Right JoyStick
    48: ("RX", -1),
    52: ("RX", +1),
    50: ("RY", -1),
    55: ("RY", +1),
}

TRIGGER_MAPPING = {66: "LT", 68: "RT"}
